site_name: Lester Zhang
site_description: Jiachen Zhang's personal website.
site_author: 张嘉宸
# site_url:

copyright: Copyright &copy; 2024 <a href="">Jiachen Zhang</a>


theme:
  name: material
  language: zh
  custom_dir: overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: 切换深色主题
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换浅色主题
  features:
    - announce.dismiss
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - toc.follow
    - navigation.prune
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
  icon:
    annotation: material/information-variant-circle


nav:
  - 主页: index.md
  - 学术研究:
      - research.md
  - 研究笔记:
      - posts/index.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/daisymilo/LesterZhang


plugins:
  - search
  - blog:
      blog_dir: posts
      post_url_format: "{slug}"
      archive_toc: true
      categories_toc: true
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tags:
      tags_file: tags.md

markdown_extensions:
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
